{
 "title": "Kubernetes / Persistent Volumes Overview",
 "tags": [
  "Kubernetes",
  "Infrastructure"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{},namespace)"
    }
   },
   {
    "name": "volume",
    "label": "PersistentVolumeClaim",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$Cluster\",namespace=\"$namespace\"},persistentvolumeclaim)"
    }
   },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Used Percentage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"$Cluster\",persistentvolumeclaim=\"$volume\"}\n/\nkubelet_volume_stats_capacity_bytes{cluster=\"$Cluster\",persistentvolumeclaim=\"$volume\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Capacity (bytes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{cluster=\"$Cluster\",persistentvolumeclaim=\"$volume\",job=\"kubernetes-nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Used Space (bytes)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"$Cluster\",namespace=\"$namespace\", persistentvolumeclaim=\"$volume\",job=\"kubernetes-nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Volumes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubelet_volume_stats_capacity_bytes{cluster=\"$Cluster\",job=\"kubernetes-nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV in Unbound State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{phase=\"Pending\",job=\"kube-state-metrics\"} == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV in Released State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolume_status_phase{phase=\"Released\",job=\"kube-state-metrics\"} == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Greater Than 80% Usage [1d]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * \n(\nsum by (persistentvolumeclaim)(avg_over_time(kubelet_volume_stats_used_bytes{cluster=~\"$Cluster\",job=\"kubernetes-nodes\"}[3d]))\n/\nsum by (persistentvolumeclaim)(avg_over_time(kubelet_volume_stats_capacity_bytes{cluster=~\"$Cluster\",job=\"kubernetes-nodes\"}[3d]))\n)\n > 80\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{cluster=~\"$Cluster\",namespace=~\"$namespace\",job=\"kubernetes-nodes\"}/1024/1024/1024)\n\n",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "PV's Full in 2 days - Usage [1d]",
   "type": "stat",
   "description": "Namespace",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(predict_linear(kubelet_volume_stats_available_bytes{cluster=\"$Cluster\",job=\"kubernetes-nodes\"}[1d], 2 * 24 * 3600) < 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}