{
 "title": "Kubernetes Cluster Monitoring Copy",
 "description": "Uses Victoria Metrics as DS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Service",
    "query": {
     "query": "query_result(sum(kube_deployment_labels{namespace=~\"$namespace\",cluster=~\"$cluster\"} OR kube_statefulset_labels{namespace=~\"$namespace\",cluster=~\"$cluster\"})  by (deployment, statefulset))"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(cadvisor_version_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod CrashLoopBackOff [15m]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod,namespace)(max_over_time(kube_pod_container_status_waiting_reason{job=\"kube-state-metrics\",namespace=~\"$namespace\",reason=\"CrashLoopBackOff\",cluster=~\"$cluster\"}[15m])>=1)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Pod CPU throttled percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100* (sum(increase(container_cpu_cfs_throttled_periods_total{cluster=~\"$cluster\"}[5m])) by (pod) / sum(increase(container_cpu_cfs_periods_total{cluster=~\"$cluster\"}[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CrashLoopBackOff [15m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod,namespace)(max_over_time(kube_pod_container_status_waiting_reason{job=\"kube-state-metrics\",namespace=~\"$namespace\",reason=\"CrashLoopBackOff\",cluster=~\"$cluster\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU (1m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"}[1m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",kubernetes_io_hostname=~\"^$node$\",cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Pods Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pods CPU Limit Usage Percent (1m avg) ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\",namespace=~\"$namespace\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{resource=\"cpu\",cluster=~\"$cluster\",pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\",namespace=~\"$namespace\"}) by (pod))",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Pods Memory Limit Usage Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\n(sum(container_memory_working_set_bytes{namespace=~\"$namespace\",cluster=~\"$cluster\",pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\"}) by (pod)\n/\nsum(kube_pod_container_resource_limits{resource=\"memory\",namespace=~\"$namespace\",cluster=~\"$cluster\",pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\"}) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Containers Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Containers CPU Usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*$\",kubernetes_io_hostname=~\"^$node$\", namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\", container!=\"POD\",cluster=~\"$cluster\"}[1m])) by (container, pod)",
     "legendFormat": "{{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Containers Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*$\",kubernetes_io_hostname=~\"^$node$\", namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\", container!=\"POD\",cluster=~\"$cluster\"}) by (container, pod)",
     "legendFormat": "{{ pod }} | {{ container }}"
    }
   ]
  },
  { "title": "Container Requests & Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Containers CPU Request & Limit",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{node=~\"^$node$\", namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\", resource=\"cpu\"}) by(container)",
     "legendFormat": "Request: {{ container }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{node=~\"^$node$\", namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\", resource=\"cpu\"}) by(container)",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Containers Memory Request & Limit",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_requests{node=~\"^$node$\", namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\", resource=\"memory\",cluster=~\"$cluster\"}) by(container)",
     "legendFormat": "Request: {{ container }}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{node=~\"^$node$\", namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\", resource=\"memory\",cluster=~\"$cluster\",cluster=~\"$cluster\"}) by(container)",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  { "title": "Container Restarts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Total Container Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\",cluster=~\"$cluster\"}[1h]))"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"^$namespace$\", pod=~\"^${deployment:regex}-([a-z0-9]+-[a-z0-9]+|[a-z0-9]+)$\",cluster=~\"$cluster\"}[$__range])) by (container, pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}